[platformio]
default_envs = esp32dev
src_dir = src

[env:esp32dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_deps =
  https://github.com/bblanchon/ArduinoJson/archive/refs/tags/v7.4.2.zip
  https://github.com/knolleary/pubsubclient/archive/refs/tags/v2.8.zip
  https://github.com/thewhobox/arduino-dali/archive/862b2c255ed8d1d269ad73fd508b5d8524414d06.zip
  https://github.com/khoih-prog/TimerInterrupt_Generic/archive/refs/tags/v1.13.0.zip
build_flags =
  -Wall
  -Wextra
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_LOOP_STACK_SIZE=24576
  -DDALI_TIMER=1
  -DDALI_NO_COMMISSIONING
